### ISSUE TITLE
Potential case-insensitive import collision

### ISSUE THREAD

**Issue by unknwon** [Xiangrui2019/go-kahla-bot-server#1]
Due to GitHub handle change (to lowercase) for long term purpose, `go get` may fail fetching `github.com/Unknwon/com`. 
Please consider take some time to update it to `github.com/unknwon/com` in the `go.mod` file.
I truly apology for the inconvenience and unintended troubles caused.

**Comment by Xiangrui2019** [comment]
无闻大佬,我明白了,我马上修改

**Comment by Xiangrui2019** [comment]
fix it.
